#ifndef GEOMETRY_H
#define GEOMETRY_H

#include <vector>
#include <string>
#include "density_map.h"

namespace mc {

// ─────────────────────────────────────────────────────────────────────────────
// 1D Geometry — original slab-based phantom (backward compatible)
// ─────────────────────────────────────────────────────────────────────────────

struct MaterialLayer {
    double start_pos; // Start position [cm]
    double end_pos;   // End position [cm]
    double density;   // Mass density [g/cm^3]
    double I_value;   // Mean excitation potential [eV] (ICRU Report 37)
    double Z_over_A;  // Z/A ratio (default: water = 0.5551)
};

class Geometry {
public:
    Geometry(double setup_uncertainty_cm = 0.0);

    // Build the default thoracic phantom: soft tissue + lung + posterior tissue
    void build_default_thoracic();

    // Apply a rigid patient positioning shift (simulates interfraction setup error)
    void apply_setup_uncertainty(double random_shift_cm);

    // Query material properties at depth x [cm]
    double get_density  (double x, double& out_I_value) const;  // legacy signature
    double get_properties(double x, double& out_I_value) const; // alias
    double get_Z_over_A  (double x) const;

    double get_max_depth() const;

private:
    std::vector<MaterialLayer> layers;
    double global_shift;
    double max_depth;
};

// ─────────────────────────────────────────────────────────────────────────────
// 2D Geometry — wraps an external DensityMap loaded from disk
// ─────────────────────────────────────────────────────────────────────────────

class Geometry2D {
public:
    // Load geometry from a binary density map file (generated by generate_phantom.py)
    explicit Geometry2D(const std::string& density_map_path);

    // Query material properties at continuous position (x=depth, y=lateral) [cm]
    double get_density  (double x, double y) const;
    double get_I_value  (double x, double y) const;
    double get_Z_over_A (double x, double y) const;

    // Physical bounds [cm]
    double get_max_depth()   const;
    double get_max_lateral() const;

    // Grid dimensions (for dose scoring)
    int get_nx() const { return map.nx; }
    int get_ny() const { return map.ny; }
    double get_dx() const { return map.dx; }
    double get_dy() const { return map.dy; }

private:
    DensityMap map;
};

} // namespace mc

#endif // GEOMETRY_H
